### ISSUE TITLE
Known Issues May 8th report

### ISSUE THREAD

**Issue by ReynBolt** [ProditorMagnus/Ageless-for-1-14#35]
- [x] Tyr'hai riders and advancement trample XP bugs
Anytime this attack is used attacker will not gain any XP, also in case of a kill there will not be any XP reward for archieving the kill. Defender gains fight xp.

- [x] Lv2 Nighstalker and Lv3 Baroness of the Night's spurt is broken
For some reason, it's working in any time of day when skill says it should be working only in night time (only lv1 is not broken and working correctly)

- [x] Thrallment is working correctly on unit it should not.
Thrallment is broken as well, and it's working in Kthons, Vampires or other living units that are meant to be inmune to plague.

**Mentioned in May 18th**

4. certain EoMa starting leaders starts with negative traits (such as lv2 Punisher, and few other cases) because I convinced to inferno8 that some units as starting leader was leading to slight advantages. Same occurs in Heroic EoMa.

5. EFM AMLA values (oftenly 100) being too low enough to require inteligent trait units to AMLA at least once before being capable to gain +strikes upgrades in XP mod in 70% XP modifier ... this is pretty akward for gameplay ... **I'm actually fixing this 5. irregularity.**

6. might be a good idea to reimplement un-upgradable nerfs on EoMa units, still I will DM inferno8 to convince him to make lv3 Infernal Vortex 14-1 ranged attack into a 8-2 to decrease XP mod strikes abuse.

**Comment by ProditorMagnus** [comment]
- [x] https://github.com/ProditorMagnus/Ageless-for-1-14/commit/5283351efdca68e4b332b77f410f664488843cc2#r112885801

**Comment by ReynBolt** [comment]
Forgot to mention issue 4th in last report, still I was aware of it. And rebalancing stuff I found EFM AMLA problems difficulting XP Mod strikes in many cases.

**Comment by ProditorMagnus** [comment]
Compromise for 6. could be to have comment in the EoMa attacks that ageless import script should change to unupgradable. Then it does not affect EoMa gameplay in any way.

**Comment by ProditorMagnus** [comment]
5. I once capped xp values to level*50

**Comment by ProditorMagnus** [comment]
- [x] fix BMR statue ability.
Changed resistance to dummy, but seems there was nothing wrong anyways

**Comment by ProditorMagnus** [comment]
4. just like 6. will not be manually changed.

**Comment by ReynBolt** [comment]
Ravana you know if you can run again a Script for lv3 AMLAs value? I don't want to manually edit ALL lv3 units having 100 or lower AMLA XP , but many Lv3 EFM units have 100 XP to AMLA on lv3 , which only in this era I'm going to fix manually, but there are a lot of already reviewed era units that some of them may have 100 XP to AMLA on lv3's ... and even lv4's ???

Not sure if to do something with lv2 that if gaining inteligent trait cannot gain +strikes upgrades from XP mod at 70% modifier because of being exactly 56 value to AMLA. Other solution could be making defualt AMLA XP be 120 so inteligent ones don't waste their chances to gain strikes upgrades if gaining inteligent trait.

Also lv2 case is not grave at all, as players would avoid getting these lv2 and avoiding to waste inteligent trait if there is another option with higher level ups ... only problem would be these lv2 that are forced to optios with no lv3's.

In other release I want to readjust manually AMLA XP for all AMLA units based in units "tier" as I already did with EoMa , so in case of running this script please avoid EoMa units because they got adjusted manually.

**Comment by ProditorMagnus** [comment]
It is detection kind of script, not directly editing. I can select units of specific level https://github.com/ProditorMagnus/WML_tree_tools/blob/master/py_files/generate_orocia_lists.py#L68 and then add alert in case xp rule is violated https://github.com/ProditorMagnus/WML_tree_tools/blob/master/py_files/find_patterns.py#L237.

**Comment by ProditorMagnus** [comment]
From: [IPS](https://forums.wesnoth.org/memberlist.php?mode=viewprofile&u=119489&sid=0f418080c77a15793eccb08c5ea5b08e)
Recipient: [Ravana](https://forums.wesnoth.org/memberlist.php?mode=viewprofile&u=129456&sid=0f418080c77a15793eccb08c5ea5b08e) 

There are few things that I think that posting here could be of help.

1.- Many lv3 units still have 100 XP on max lv3 , if XP is equal or lower than 126 in an unit that lready is max level increase the XP to AMLA to 126 (with some kind of script?) as 126 in 70% XP modifier is 88 , or just set to 150.

2.- Thrallment will work on living units that are meant to be inmune to plague (pretty obvious , but wanted to re-mention what's the exact issue)

3.- Realized about some MERCS units having weird unit properties like 3 MP cost in sand, 30% defense in moats ... will have to carefully check these foot types and find a logic way for each faction ... but I would preffer viewing factions with 20% sand defense but 2 MP cost instead of the opposite because too high movement cost requeriment in a terrain that in some situations is too common is unfun to play.

I guess rest is too obvious/already listed so there is no need to re-mention them, or in other cases not that relevant.

**Comment by ReynBolt** [comment]
I'm about to do the re-design of MERCS foot , manually changed to something that feels more predictible and logical in each faction ... this took me real long LOL , a whole afternoon.

**Comment by ProditorMagnus** [comment]
Rest of the topics did not seem specific enough to change anything.
